[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "compressed-image"
version = "0.1.0"

[tool.scikit_build_core]
wheel.install-dir = "compressed_image"